version: "3"
services:
  api:
    environment:
      DEBUG: 1
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/code/app
    depends_on:
      - db
  db:
    ports:
      - "5678:5678"
