version: '3'
services:
  api:
    environment:
      FURDB_HOST: http://db
      FURDB_PORT: 8080
      FURDB_DATABASE_ID: dictionary
      FURDB_TABLE_ID: dictionary
    build: .
    working_dir: /code/app
    ports:
      - "5000:80"
    restart: on-failure
  db:
    image: madhavanraja/furdb:0.1.1
    environment:
      FUR_DIRECTORY: /furdb
      FURDB_PORT: 8080
    restart: on-failure
