version: "3"
services:
  api:
    container_name: api
    environment:
      FURDB_HOST: http://db
      FURDB_PORT: 5678
      FURDB_DATABASE_ID: dictionary
      FURDB_TABLE_ID: dictionary
    build: .
    working_dir: /code/app
    ports:
      - "5000:80"
    restart: on-failure
  db:
    container_name: db
    image: madhavanraja/furdb:0.1.2-alpha
    environment:
      WORKDIR: /furdb
      PORT: 5678
    restart: on-failure
