version: '3'
services:
  api:
    environment:
      FURDB_HOST: http://host.docker.internal
      FURDB_PORT: 8080
      FURDB_DATABASE_ID: dictionary
      FURDB_TABLE_ID: dictionary
      DEBUG: 1
    build: .
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/code/app
    ports:
      - "5000:80"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
